receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

exporters:
  jaeger:
    endpoint: http://jaeger:14268/api/traces
    tls:
      insecure: true
  prometheus:
    endpoint: "0.0.0.0:9464"
    namespace: tbd
  debug:
    verbosity: basic

service:
  telemetry:
    metrics:
      address: 0.0.0.0:13133
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [jaeger, debug]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus, debug]
