global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'api'
    static_configs:
      - targets: ['api:8080']

  - job_name: 'worker'
    static_configs:
      - targets: ['worker:2112']

  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:9464']
